require('dotenv').config();
const mongoose = require('mongoose');
const Property = require('./models/Property');
const Testimonial = require('./models/Testimonial');

mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/nestlux')
  .then(() => {
  console.log('Connected to MongoDB for seeding');
  seedDB();
}).catch(err => {
  console.error('MongoDB connection error:', err);
});

const properties = [
  {
    title: 'Modern Family Home',
    description: 'A beautiful modern home perfect for families.',
    price: 850000,
    type: 'House',
    status: 'For Sale',
    location: 'Los Angeles, CA',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2500,
    images: ['https://picsum.photos/seed/house1/800/600'],
    amenities: ['Pool', 'Garage', 'Garden'],
    featured: true,
  },
  {
    title: 'Luxury Villa with Ocean View',
    description: 'Stunning villa offering breathtaking ocean views.',
    price: 2500000,
    type: 'Villa',
    status: 'For Sale',
    location: 'Malibu, CA',
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4500,
    images: ['https://picsum.photos/seed/villa2/800/600'],
    amenities: ['Ocean View', 'Infinity Pool', 'Gym', 'Smart Home'],
    featured: true,
  },
  {
    title: 'Cozy Downtown Apartment',
    description: 'Perfect location in the heart of the city.',
    price: 3200,
    type: 'Apartment',
    status: 'For Rent',
    location: 'New York, NY',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    images: ['https://picsum.photos/seed/estate3/800/600'],
    amenities: ['Gym', 'Doorman', 'Rooftop'],
    featured: false,
  },
  {
    title: 'Spacious Suburban Estate',
    description: 'Huge estate with plenty of outdoor space.',
    price: 1200000,
    type: 'Estate',
    status: 'For Sale',
    location: 'Austin, TX',
    bedrooms: 6,
    bathrooms: 5,
    sqft: 5000,
    images: ['https://picsum.photos/seed/luxury4/800/600'],
    amenities: ['Tennis Court', 'Guest House', 'Home Theater'],
    featured: true,
  },
  {
    title: 'Chic Loft Studio',
    description: 'Industrial style loft with high ceilings.',
    price: 2800,
    type: 'Studio',
    status: 'For Rent',
    location: 'Chicago, IL',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 850,
    images: ['https://picsum.photos/seed/mansion5/800/600'],
    amenities: ['Exposed Brick', 'Large Windows', 'In-unit Laundry'],
    featured: false,
  },
  {
    title: 'Elegant Penthouse',
    description: 'Top floor penthouse with panoramic city views.',
    price: 4500000,
    type: 'Penthouse',
    status: 'For Sale',
    location: 'Miami, FL',
    bedrooms: 3,
    bathrooms: 4,
    sqft: 3200,
    images: ['https://picsum.photos/seed/penthouse6/800/600'],
    amenities: ['Private Elevator', 'Terrace', 'Concierge'],
    featured: true,
  },
  {
    title: 'Beachfront Condo',
    description: 'Steps away from the sand with a private balcony.',
    price: 650000,
    type: 'Condo',
    status: 'For Sale',
    location: 'San Diego, CA',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    images: ['https://picsum.photos/seed/condo7/800/600'],
    amenities: ['Beach Access', 'Pool', 'Parking'],
    featured: false,
  },
  {
    title: 'Classic Craftsman Bungalow',
    description: 'Charming historic home with modern updates.',
    price: 720000,
    type: 'Bungalow',
    status: 'For Sale',
    location: 'Portland, OR',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    images: ['https://picsum.photos/seed/bungalow8/800/600'],
    amenities: ['Fireplace', 'Hardwood Floors', 'Fenced Yard'],
    featured: false,
  },
  {
    title: 'Modern Townhouse',
    description: 'Three-story townhouse in a quiet neighborhood.',
    price: 550000,
    type: 'Townhouse',
    status: 'For Sale',
    location: 'Denver, CO',
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2000,
    images: ['https://picsum.photos/seed/townhouse9/800/600'],
    amenities: ['Rooftop Deck', 'Attached Garage', 'Smart Tech'],
    featured: false,
  },
  {
    title: 'Minimalist Studio Apartment',
    description: 'Compact and efficient living space.',
    price: 1800,
    type: 'Studio',
    status: 'For Rent',
    location: 'Seattle, WA',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 500,
    images: ['https://picsum.photos/seed/studio10/800/600'],
    amenities: ['Bike Storage', 'Fitness Center', 'Co-working Space'],
    featured: false,
  },
  {
    title: 'Mediterranean Villa',
    description: 'Stunning architecture with a lush courtyard.',
    price: 1800000,
    type: 'Villa',
    status: 'For Sale',
    location: 'Santa Barbara, CA',
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3800,
    images: ['https://picsum.photos/seed/villa11/800/600'],
    amenities: ['Courtyard', 'Wine Cellar', 'Spa'],
    featured: true,
  },
  {
    title: 'Spacious Duplex',
    description: 'Great investment opportunity or multi-generational living.',
    price: 950000,
    type: 'Duplex',
    status: 'For Sale',
    location: 'Boston, MA',
    bedrooms: 6,
    bathrooms: 4,
    sqft: 3000,
    images: ['https://picsum.photos/seed/duplex12/800/600'],
    amenities: ['Separate Entrances', 'Backyard', 'Off-street Parking'],
    featured: true,
  },
  {
    title: 'Luxury South Mumbai Apartment',
    description: 'Premium sea-facing apartment in the heart of South Mumbai.',
    price: 5000000,
    type: 'Apartment',
    status: 'For Sale',
    location: 'Mumbai, Maharashtra',
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3200,
    images: ['https://picsum.photos/seed/mumbai1/800/600'],
    amenities: ['Sea View', 'Gym', 'Parking', 'Security'],
    featured: true,
  },
  {
    title: 'Delhi Golf Links Estate',
    description: 'Spacious independent house in Golf Links with lush greenery.',
    price: 8000000,
    type: 'House',
    status: 'For Sale',
    location: 'New Delhi, Delhi',
    bedrooms: 6,
    bathrooms: 6,
    sqft: 6500,
    images: ['https://picsum.photos/seed/delhi1/800/600'],
    amenities: ['Garden', 'Servant Quarters', 'Private Terrace'],
    featured: true,
  },
  {
    title: 'Bangalore Tech Park Villa',
    description: 'Modern villa near major tech parks with smart home features.',
    price: 2000000,
    type: 'Villa',
    status: 'For Sale',
    location: 'Bangalore, Karnataka',
    bedrooms: 4,
    bathrooms: 4,
    sqft: 4000,
    images: ['https://picsum.photos/seed/bangalore1/800/600'],
    amenities: ['Smart Home', 'Clubhouse', 'Pool'],
    featured: true,
  },
];

const testimonials = [
  {
    name: 'Rajesh Kumar',
    role: 'Homebuyer',
    rating: 5,
    quote: 'NestLux made finding our dream home a breeze. Their service is truly premium.',
    avatar: 'RK',
  },
  {
    name: 'Priya Sharma',
    role: 'Property Investor',
    rating: 5,
    quote: 'I rely on NestLux for all my property investments. Expert agents and verified listings.',
    avatar: 'PS',
  },
  {
    name: 'Amit Patel',
    role: 'Seller',
    rating: 4,
    quote: 'They sold my house in record time. The presentation and marketing were top-notch.',
    avatar: 'AP',
  },
  {
    name: 'Sneha Gupta',
    role: 'First-time Buyer',
    rating: 5,
    quote: 'As a first-time buyer, I felt supported throughout the entire process. Thank you, NestLux!',
    avatar: 'SG',
  },
  {
    name: 'Vikram Singh',
    role: 'Renter',
    rating: 5,
    quote: 'Found an amazing apartment in the city center. The team was very responsive.',
    avatar: 'VS',
  },
  {
    name: 'Anjali Desai',
    role: 'Business Owner',
    rating: 5,
    quote: 'Their commercial property team is knowledgeable and professional. Highly recommended.',
    avatar: 'AD',
  },
  {
    name: 'Rahul Mehta',
    role: 'Homebuyer',
    rating: 4,
    quote: 'Great selection of properties and a very smooth closing process.',
    avatar: 'RM',
  },
  {
    name: 'Kavita Reddy',
    role: 'Seller',
    rating: 5,
    quote: 'I was impressed by their attention to detail and market expertise.',
    avatar: 'KR',
  },
];

async function seedDB() {
  try {
    await Property.deleteMany({});
    await Testimonial.deleteMany({});
    
    await Property.insertMany(properties);
    await Testimonial.insertMany(testimonials);
    
    console.log('Database seeded successfully');
  } catch (error) {
    console.error('Error seeding database:', error);
  } finally {
    mongoose.connection.close();
  }
}
